name: GitHub Actions Vercel Preview

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:

jobs:
  Test:
    uses: RileyBax/CISE_SPEED_W207_01/.github/workflows/test.yml@develop

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - uses: actions/checkout@v3

      # Install backend dependencies and build backend
      - name: Install and Build Backend
        run: |
          cd backend
          npm install
          npm run build

      # Install frontend dependencies and build frontend
      - name: Install and Build Frontend
        run: |
          cd ../frontend
          npm install
          npm run build

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
