name: GitHub Actions Test

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install backend dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        run: |
          cd ../frontend
          npm install

      # Run backend tests
      - name: Run Backend Tests
        run: |
          cd ../backend
          npm test

      # Run frontend tests
      - name: Run Frontend Tests
        run: |
          cd ../frontend
          npm test
